name: CI Backend

on:
  push:
    branches:
      - develop
      - main
      - "feature/**"
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      DB_NAME: ${{ secrets.DB_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EXPIRES_IN: ${{ secrets.EXPIRES_IN }}
      SENHA_USUARIO: ${{ secrets.SENHA_USUARIO }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências
        run: npm install

      - name: Subir API em background
        run: npm start &

      - name: Esperar API ficar disponível
        run: npx wait-on http://localhost:3000

      - name: Rodar testes
        run: npm test